### ISSUE TITLE
Font bug

### ISSUE THREAD

**Issue by silvestrinidev** [Fro-Q/Qlean#1]
![image](https://github.com/Fro-Q/Qlean/assets/86329735/7d9a03f2-4a53-4232-b247-4809db95c6ea)
![image](https://github.com/Fro-Q/Qlean/assets/86329735/546f3574-b2bc-441f-a9ea-9bc8dbfc77d4)

**Comment by froq0** [comment]
Hey there! Could you please describe the bug you encountered clearer? I can hardly tell what was going on according to the screenshots you offered.

**Comment by dhniceday** [comment]
I can confirm this bug also. All headers in the interface are broken. It seems that a font is hardcoded somewhere, but that font doesn't exist on my system. So it defaults to this serif font, instead of the font chosen in "Interface Font". I have chosen Inter in Interface Font (Obsidian settings) and Inter in Interface Font (Style Settings).
I am using Ubuntu 24.04.

**Comment by dhniceday** [comment]
I fixed it locally on my end. Adding fonts to --font-default didn't work, so I commented the line 2675.
  /*font-family: --font-default;*/

That fixed the interface fonts.
